name: Build Images
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
        - uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: DeterminateSystems/nix-installer-action@main
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - name: Push Builder
          run: |
            docker load < $(nix-build build/builder-container.nix)
            docker tag grouphp:latest ghcr.io/${{ github.repository }}/builder:${{ github.ref_name }}
            docker push ghcr.io/${{ github.repository }}/builder:${{ github.ref_name }}

        # TODO: build the final image
#        - name: Login to Docker Hub
#          uses: docker/login-action@v3
#          with:
#            username: ${{ secrets.DOCKERHUB_USERNAME }}
#            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
              push: false # TODO: push the images to a registry
              tags: user/app:latest
              build-args: |
                BUILDER=ghcr.io/${{ github.repository }}/builder:${{ github.ref_name }}
