name: Base
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
    Builder:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
        - uses: actions/checkout@v4
        - uses: docker/setup-qemu-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: DeterminateSystems/nix-installer-action@main
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - name: Push Builder
          run: |
            docker load < $(nix-build build/builder-container.nix)
            docker tag grouphp:latest ghcr.io/${{ github.repository }}/builder:${{ inputs.ref }}
            docker push ghcr.io/${{ github.repository }}/builder:${{ inputs.ref }}
